import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class AnimationImageData {
    public static ArrayList<Image> explosionsBigImage;
    public static ArrayList<Image> explosionsSmallImage;

    //Create explosion Big
    public static ArrayList<Image> createExplosionBig() {
        explosionsBigImage = new ArrayList<>();
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion101.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion102.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion103.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion104.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion105.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion106.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion108.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion109.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion110.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion111.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion112.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion113.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion114.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion115.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion116.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion117.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion118.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion119.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion120.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion121.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion122.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion123.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion124.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion125.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion126.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion127.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion128.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion129.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion130.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion131.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion132.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion133.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion134.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion135.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion136.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion137.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion138.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion139.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion140.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion141.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion142.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion143.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion144.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion145.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion146.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion147.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion148.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion149.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion150.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion151.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion152.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion153.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion154.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion155.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion156.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion157.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion158.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion159.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion160.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion161.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion162.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion163.png").getImage());
        explosionsBigImage.add(new ImageIcon("Image/explosions/big/explosion164.png").getImage());
        return explosionsBigImage;
    }

    public static ArrayList<Image> createExplosionSmall(){
        explosionsSmallImage = new ArrayList<>();
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion1.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion2.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion3.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion4.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion5.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion6.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion7.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion8.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion9.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion10.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion11.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion12.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion13.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion14.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion15.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion16.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion17.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion18.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion19.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion20.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion21.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion22.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion23.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion24.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion25.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion26.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion27.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion28.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion29.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion30.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion31.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion32.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion33.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion34.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion35.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion36.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion37.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion38.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion39.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion40.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion41.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion42.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion43.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion44.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion45.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion46.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion47.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion48.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion49.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion50.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion51.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion52.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion53.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion54.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion55.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion56.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion57.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion58.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion59.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion60.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion61.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion62.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion63.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion64.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion1.png").getImage());
        explosionsSmallImage.add(new ImageIcon("Image/explosions/small/explosion1.png").getImage());
        return explosionsSmallImage;
    }


}
